имя: КИ
вкл:
  толкать:
    ответвления: [ главная ]

Вакансии:
  строить:
    работает: ubuntu-последняя версия

    шаги:
 - использует: действия/оформить заказ@v2

      # используется для кэширования зависимостей с таймаутом
 - имя: Дата получения
        идентификатор: дата получения
        выполнить: |
 echo "::set-output name=дата::$(/bin/date -u "+%Y%m%d")"
        оболочка: bash

 - имя: Глобальный каталог Cache Buildozer
        использует: действия/кэш@v2
        с:
          путь: .buildozer_global
          ключ: buildozer-global-${{ hashFiles('buildozer.spec') }} # Замените на свой путь

 - использует: действия/кэш@v2
        с:
          путь: .buildozer
          ключ: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

 - название: Сборка с помощью Buildozer
        использует: ArtemSBulgakov/buildozer-action@v1
        идентификатор: buildozer
        с:
          команда: buildozer android debug
          buildozer_version: мастер

 - название: Загружать артефакты
        использование: действия/загрузка-артефакт@v2
        с:
          название: пакет
          путь: ${{ steps.buildozer.выходы.имя_файла }}
